--실행 AIT + X
CREATE TABLE V1_BOARD(BRO_NO NUMBER primary key,
BRD_TITLE VARCHAR2(20),BRD_WRITER VARCHAR2(20), BRD_CONTENT CLOB,
BRD_HIT NUMBER, BRD_IMG BLOB, 
BRD_DATE DATE,BRD_FILE VARCHAR2(200));

--시퀀스 생성
CREATE SEQUENCE SEQ_V1_BOARD_NO 
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

ALTER SEQUENCE SEQ_V1_BOARD_NO  INCREMENT BY 1;

COMMIT; 

SELECT * FROM V1_BOARD;

INSERT INTO V1_BOARD VALUES
(SEQ_V1_BOARD_NO.NEXTVAL, '제목12','tre','내용은 내용이고 내용이다',2, NULL, SYSDATE);